estimator:
  pickle: model.pickle

strategy:
  name: gp
  params:
    seeds: 5
    kernels:
        - { name : GPy.kern.Matern52, params : {ARD : True}, options: {independent : False} }
        - { name : GPy.kern.Bias, params : {}, options: {independent : False} }
        - { name : GPy.kern.White, params : {}, options: {independent : False} }
    acquisition: { name : ei, params : {kappa: 0} }
    n_iter: 20
    n_init: 10
    max_iter: 20
    predict_from_gp: True

search_space:
  atomcenteredsymmetryfunctions__nbasis:
    min: 6
    max: 30
    type: int
    warp: log

  atomcenteredsymmetryfunctions__cutoff:
    min: 3
    max: 5
    type: float
    warp: log

  atomcenteredsymmetryfunctions__precision:
    min: 1.05
    max: 3
    type: float
    warp: log

  neuralnetwork__hl1:
    min: 30
    max: 500
    type: int
    warp: log

  neuralnetwork__batch_size:
    min: 10
    max: 200
    type: int
    warp: log

  neuralnetwork__iterations:
    min: 300
    max: 5000
    type: int
    warp: log

  neuralnetwork__learning_rate:
    min: 4e-4
    max: 3e-3
    type: float
    warp: log

  neuralnetwork__l2_reg:
    min: 1e-8
    max: 4e-4
    type: float
    warp: log

  neuralnetwork__l1_reg:
    min: 1e-7
    max: 1e-2
    type: float
    warp: log

cv:
  name: GroupKFold
  params:
    n_splits: 3
    group_filename: groups.csv

dataset_loader:
  name: dsv
  params:
    filenames: idx.csv

trials:
    uri: sqlite:///osprey-trials1.db

